FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore LocalCart.sln
RUN dotnet publish src/Services/Auth/LocalCart.Auth.Api/LocalCart.Auth.Api.csproj \
    --configuration Release \
    --no-restore \
    --output /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

ENV ASPNETCORE_URLS=http://0.0.0.0:10000 \
    DOTNET_EnableDiagnostics=0
EXPOSE 10000

COPY --from=build --chown=app:app /app/publish .
USER app

ENTRYPOINT ["dotnet", "LocalCart.Auth.Api.dll"]

